### ISSUE TITLE
windows.bed

### ISSUE THREAD

**Issue by arvkevi** [rgcgithub/clamms#1]
Hello, I've followed instructions up to the point of creating the windows.bed file.  Can you lend any insight to the "NoneType" error in the python script?  I've included the first few lines of output by removing the '>windows.bed' from the end of the command.

Thank you!

kevin@Kevin-ubuntu:~$ $CLAMMS_DIR/annotate_windows.sh /home/kevin/reference/exomesorted.bed /home/kevin/reference/human_g1k_v37.fasta /home/kevin/clamms/100mer_mappability_sorted.bed $INSERT_SIZE clamms/clamms_special_regions_sorted.bed
1   14642   14882   1:14642-14882   130 0.650   0.194   3
1   14943   15063   1:14943-15063   118 0.590   0.125   3
1   15751   15990   1:15751-15990   130 0.649   0.494   3
1   16599   16719   1:16599-16719   133 0.665   0.128   3
1   16834   17074   1:16834-17074   118 0.592   0.138   3
1   17211   17331   1:17211-17331   117 0.585   0.125   3
...
Traceback (most recent call last):
  File "/home/kevin/clamms//calc_window_mappability.py", line 54, in <module>
    while value[0] != window[0]:
TypeError: 'NoneType' object has no attribute '**getitem**'

--update--
the clamms_special_regions.bed was unsorted.
$sort -V -k1,1 -k2,2n clamms_special_regions.bed > clamms_special_regions_sorted.bed
Only after performing that command on all 3 bed files (targets, mappability, and special_regions) did the script execute successfully.  Issues resolved, thanks for reading.

**Comment by arvkevi** [comment]
The 100mer_mappability_sorted.bed was unsorted upon download.  I ran bedtools sort only to be reminded that bedtools requires the 'chr' prefix in your file to sort bed's.  Currently trying to add 'chr' to all my beds, sort them, then remove 'chr' from all the sorted beds.

**Comment by rgcgithub** [comment]
Glad you got it to work. I do recommend using the sort order we specify in the README: `sort -k1,1 -k2,2n`, which is the sort used for the clamms_special_regions.bed file.

The -V option to sort forces a numeric-like sort opposed to a string sort, which is not the desired behavior to include X & Y chromosomes. However, it only matters that the input files are all sorted consistently in a manner that is compatible with bedtools.

Evan
