### ISSUE TITLE
sam_gatk_coverage_to_bed resulting in all 0's in last column

### ISSUE THREAD

**Issue by drramki-chop** [rgcgithub/clamms#7]
Here is a typical DoC output from GATK.

1:69482-69600	93	0.78	93	0.78	1	1	1	22.7	0.0	0.0	0.0	0.0	0.0	0.0
1:721382-721519	14360	104.06	14360	104.06	77	112	129	100.0	100.0	100.0	100.0	100.0	85.5	73.2
1:721531-721806	48387	175.32	48387	175.32	130	186	222	100.0	100.0	100.0	100.0	100.0	100.0	100.0
1:721852-721942	16542	181.78	16542	181.78	175	184	191	100.0	100.0	100.0	100.0	100.0	100.0	100.0
1:762096-762275	34029	189.05	34029	189.05	153	197	228	100.0	100.0	100.0	100.0	100.0	100.0	100.0

Usage:

./sam_gatk_coverage_to_bed sample.sample_interval_summary windows.bed > sample.coverage.bed

And this results in all 0's in the last column....

1	69482	69600	0
1	721382	721519	0
1	721531	721806	0
1	721852	721942	0
1	762096	762275	0
1	762281	762414	0
1	762421	762565	0
1	861267	861496	0
1	865583	865787	0
1	866332	866507	0

Wondering what's wrong here?

**Comment by rgcgithub** [comment]
sam_gatk_coverage_to_bed parses the raw DoC output file (.out), not the sample_interval_summary. Fields should look like this:
1:566346	1	1.00	1
1:566347	1	1.00	1
1:566348	2	2.00	2
1:566349	2	2.00	2

It's counting depth for CLAMMS-defined windows, not necessarily the raw exon targets, so has to go back to the per-base coverage. You can also use samtools depth output.

Evan

**Comment by drramki-chop** [comment]
Thanks. That explains it.
